"""Add spam blocklist table

Revision ID: 05d9d55a08f1
Revises: 5a3d7fec73c0
Create Date: 2026-03-15 13:53:13.439765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d9d55a08f1'
down_revision = '5a3d7fec73c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spam_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spam_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spam_blocklist_value'), ['value'], unique=True)

    with op.batch_alter_table('contact_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_submissions_is_spam'), ['is_spam'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_submissions_is_spam'))

    with op.batch_alter_table('spam_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spam_blocklist_value'))

    op.drop_table('spam_blocklist')
    # ### end Alembic commands ###
