from pathlib import Path

from curriculum import PROJECT_DETAILS as COORDINATE_PROJECTS


STATIC_ROOT = Path(__file__).with_name("static")


def step(title, task, checkpoint, mistake):
    return {
        "title": title,
        "task": task,
        "explanation": "",
        "checkpoint": checkpoint,
        "mistake": mistake,
    }


def project_entry(
    name,
    program_key,
    group,
    project_type,
    mode,
    difficulty,
    estimated_time,
    summary,
    mission,
    topics,
    what_students_build,
    what_students_learn,
    needs,
    setup_note,
    build_steps,
    test_questions,
    common_mistakes,
    improvements,
    challenge_levels,
    demonstrate,
    parent_explanation,
    lesson_slug,
    related_topics,
    status=None,
):
    return {
        "name": name,
        "program_key": program_key,
        "group": group,
        "project_type": project_type,
        "mode": mode,
        "difficulty": difficulty,
        "estimated_time": estimated_time,
        "card_summary": summary,
        "mission": mission,
        "topics": topics,
        "what_students_build": what_students_build,
        "what_students_learn": what_students_learn,
        "needs": needs,
        "setup_note": setup_note,
        "build_steps": build_steps,
        "test_questions": test_questions,
        "common_mistakes": common_mistakes,
        "improvements": improvements,
        "challenge_levels": challenge_levels,
        "demonstrate": demonstrate,
        "parent_explanation": parent_explanation,
        "lesson_slug": lesson_slug,
        "related_topics": related_topics,
        "status": status or project_type,
        "status_class": "later" if status == "Available later" else ("lab" if mode == "lab" else "active"),
    }


PROJECTS = dict(COORDINATE_PROJECTS)


PROJECTS.update(
    {
        "attack-of-the-angry-snowballs": project_entry(
            "Attack of the Angry Snowballs",
            "scratch",
            "Scratch",
            "Guided Class Project",
            "guided",
            "Beginner / Builder",
            "45-70 minutes",
            "Defend a mug of cocoa from falling snowballs. Each wave gets faster, and winter becomes less reasonable.",
            "Move the catcher, survive the changing attack patterns, and keep the town's emergency cocoa out of the snow.",
            ["Loops", "Randomness", "Coordinates", "Collision", "Score", "Timing"],
            ["A controllable catcher", "Repeated falling snowballs", "Random starting positions", "Collision and missed-object rules", "Score and loss state", "Reliable restart"],
            ["Choosing a loop", "Random x positions", "Changing y over time", "Collision checks", "Variables and difficulty", "Testing repeated events"],
            ["Browser", "Scratch editor", "Keyboard", "Student-drawn or ordinary built-in assets"],
            "The project works with built-in or student-drawn artwork. Saving and sharing depend on the classroom setup.",
            [
                step("Create the catcher", "Put a player-controlled catcher near the bottom of the stage.", "The left and right controls work without leaving the stage.", "Changing y instead of x."),
                step("Make one snowball fall", "Start one snowball above the stage and change its y position inside a loop.", "The snowball crosses the stage from top to bottom.", "Moving once instead of inside a loop."),
                step("Move the next attack", "Choose a new x position before each fall.", "Several falls begin in different places.", "Choosing a new x during every movement step."),
                step("Separate catches from misses", "Write one rule for touching the catcher and another for passing the bottom edge.", "Each fall has one outcome and changes the score once.", "Scoring repeatedly while the sprites still touch."),
                step("Build the waves", "Repeat the fall-and-reset cycle, then shorten the delay after a chosen score.", "The speed changes at the score you chose.", "Making the objects too fast to test."),
                step("Reset the storm", "Restore the score, speed, positions, and game state.", "Three restarts produce the same first wave.", "Resetting the score but keeping the faster speed."),
            ],
            ["Can every snowball be caught?", "Does a miss count once?", "Can a snowball appear outside the playable area?", "Does speed change at the intended score?", "Does restart restore the first-wave timing?"],
            ["Random x changes during the fall.", "The miss line is outside the stage.", "Catch and miss happen in the same frame.", "A forever loop prevents the loss screen."],
            ["Add a rare giant snowball.", "Create two wave patterns.", "Add a temporary shield.", "Make wind change horizontal movement."],
            [{"name": "Builder", "description": "Add a survival timer."}, {"name": "Inventor", "description": "Create a readable wave system with changing delays."}, {"name": "Boss Level", "description": "Design three attack patterns and select them from game state."}],
            ["Working catcher movement", "A repeated attack", "Catch and miss outcomes", "A visible score", "One difficulty change", "One repaired loop bug"],
            "Each snowball uses the same fall-and-reset loop, but its position and timing can change. Students see why repeated systems need clear rules for scoring, stopping, and starting again.",
            "loops-and-repetition",
            ["loops-and-repetition", "variables-and-state", "sensing-and-collision"],
        ),
        "the-suspiciously-emotional-space-pet": project_entry(
            "The Suspiciously Emotional Space Pet",
            "scratch",
            "Scratch",
            "Computer Lab Project",
            "lab",
            "Builder",
            "60-90 minutes",
            "Create a virtual pet with needs that change over time and actions that affect more than one value.",
            "Keep an alien pet fed, rested, and reasonably trusting. It remains suspicious of the snack button.",
            ["Variables", "State", "Events", "Conditions", "Timers", "Messages"],
            ["At least two changing needs", "Actions that affect those needs", "Visible mood or state", "Time-based change", "A recovery path", "A reset and demonstration state"],
            ["Variables as memory", "Initialization", "Connected state changes", "Threshold decisions", "Balancing systems", "Explaining emergent behaviour"],
            ["Browser", "Scratch editor", "Keyboard or mouse", "Student-created pet design"],
            "Students choose the pet's needs, the scale for each value, and the rules connecting them. Different models are welcome if their behaviour can be explained.",
            [
                step("Choose the needs", "Define two or three values the pet must remember.", "Each variable has a clear name and starting value.", "Using vague names such as number1."),
                step("Create care actions", "Connect buttons or keys to feeding, resting, or playing.", "Each action changes the intended values once.", "One click triggers many repeated updates."),
                step("Let time matter", "Change at least one need at a controlled interval.", "The change is slow enough to observe and test.", "A forever loop changes values instantly."),
                step("Show the state", "Use expressions, messages, or animation to show when a value crosses a threshold.", "Someone watching can tell why the pet looks different.", "The visible mood disagrees with the stored values."),
                step("Test difficult combinations", "Try low energy, high hunger, and competing care actions.", "The pet always has a recoverable state.", "A value grows without a boundary."),
            ],
            ["Do all needs reset?", "Can one click update twice?", "Can values leave the intended range?", "Does the visible mood match the values?", "Can the pet recover from its lowest state?"],
            ["Needs are never initialized.", "Two scripts fight over the same state.", "Values move too quickly to understand.", "The pet becomes permanently stuck."],
            ["Add a trust variable.", "Make actions have trade-offs.", "Create a day/night state.", "Add a short care history."],
            [{"name": "Builder", "description": "Keep two needs inside sensible boundaries."}, {"name": "Inventor", "description": "Make care actions affect several needs differently."}, {"name": "Boss Level", "description": "Create named pet states from combinations of values."}],
            ["Known starting values", "Two care actions", "Time-based change", "A visible state", "A recovery path", "One explained rule trade-off"],
            "The pet remembers hunger, energy, or trust as variables. Students decide how time and care actions change those values, then trace why the pet moves from one mood to another.",
            "variables-and-score",
            ["variables-and-state", "conditions-and-decisions", "events-and-commands"],
        ),
        "the-floor-is-definitely-lava": project_entry(
            "The Floor Is Definitely Lava",
            "scratch",
            "Scratch",
            "Guided Class Project",
            "guided",
            "Builder",
            "55-80 minutes",
            "Build a one-room platform game with a controlled jump, safe platforms, lava, and a clean restart.",
            "Cross a room whose floor has become lava for reasons the building manager refuses to explain.",
            ["Sensing", "Collision", "Coordinates", "Variables", "Game State", "Debugging"],
            ["Horizontal movement", "A controlled jump", "Safe platforms", "Lava collision", "Win and loss states", "Restart logic"],
            ["Collision evidence", "Vertical movement", "State during a jump", "Boundaries", "Repeated sensing", "Testing edge cases"],
            ["Browser", "Scratch editor", "Keyboard", "Student-drawn platform map"],
            "The first version uses simple gravity and collision rules. That leaves enough code visible to inspect when a landing goes wrong.",
            [
                step("Draw the room", "Give the lava and safe surfaces clearly different colours.", "Every safe region is easy to identify.", "Using similar colours for walls and hazards."),
                step("Add horizontal movement", "Change x from keyboard input while checking stage edges.", "The player moves reliably left and right.", "Position changes continue after key release."),
                step("Build a simple jump", "Change y upward, then return downward in controlled steps.", "The jump begins and ends predictably.", "Starting another jump while already airborne."),
                step("Sense safe and dangerous contact", "Define exactly what counts as platform and lava contact.", "Each surface produces the intended state.", "Transparent costume edges trigger early."),
                step("Add finish and restart", "Create a target, win state, loss state, and complete reset.", "Win and loss cannot happen together.", "Only the player position resets."),
            ],
            ["Can the player jump forever?", "Can fast movement pass through lava?", "Can the player stand beside a platform?", "Can win and loss overlap?", "Does restart restore jump state?"],
            ["Collision is checked only once.", "The player remains marked airborne after landing.", "A platform costume has unexpected collision space.", "Gravity continues after the game ends."],
            ["Add one moving platform.", "Create a warning tile.", "Add a checkpoint.", "Design a second room with a different coordinate layout."],
            [{"name": "Builder", "description": "Add a second safe platform."}, {"name": "Inventor", "description": "Create a moving platform with reliable sensing."}, {"name": "Boss Level", "description": "Build a second stage and preserve the restart rules."}],
            ["Working movement and jump", "Visible safe and hazard regions", "Reliable loss", "Reliable win", "Complete restart", "One collision bug explained"],
            "A platformer only works when movement, surfaces, and game state agree. Students turn visible contact into exact rules, then test awkward cases such as landing beside a platform or touching lava at speed.",
            "sensing-and-collision",
            ["sensing-and-collision", "coordinates", "debugging"],
        ),
        "robot-hamster-command-centre": project_entry(
            "Robot Hamster Command Centre",
            "scratch",
            "Scratch",
            "Guided Class Project",
            "guided",
            "Beginner",
            "45-65 minutes",
            "Send movement commands to a robot hamster as it crosses a small security map.",
            "Program a robot hamster to patrol snack storage without treating every crumb as an international emergency.",
            ["Events", "Commands", "Sequences", "Coordinates", "Messages", "Debugging"],
            ["A grid-like map", "Clear movement commands", "A known start", "A target route", "Command feedback", "Reset behaviour"],
            ["Events as triggers", "Command order", "Position and direction", "Messages between scripts", "Prediction", "Sequence debugging"],
            ["Browser", "Scratch editor", "Keyboard", "Student-drawn hamster and map"],
            "The project uses Scratch to work on robot logic; no physical robot is needed.",
            [
                step("Draw the command map", "Make a simple route with a start, a target, and one obstacle.", "You can describe the whole route as a sequence of steps.", "Making the grid too small for the sprite."),
                step("Define movement commands", "Connect keys or buttons to forward and turn actions.", "Each command has one clear effect.", "Mixing position and direction changes."),
                step("Set a known start", "Reset position and direction together.", "Every attempt begins identically.", "Resetting position but not direction."),
                step("Run a sequence", "Trigger several commands in order with visible pacing.", "The hamster reaches a predictable result.", "Commands overlap because there is no timing."),
                step("Report success or collision", "Use sensing and messages to explain the outcome.", "The project distinguishes target and obstacle.", "The result message appears before movement ends."),
            ],
            ["Does each command do one thing?", "Does order matter visibly?", "Does reset restore direction?", "Can a route collide between grid points?", "Does the result wait for the sequence?"],
            ["No event starts the command sequence.", "Turns also move the hamster.", "Direction is lost after reset.", "Several key events run at once."],
            ["Add a second route.", "Display the command history.", "Allow command planning before execution.", "Create reusable route functions."],
            [{"name": "Builder", "description": "Complete a five-command route."}, {"name": "Inventor", "description": "Store a planned command sequence before running it."}, {"name": "Boss Level", "description": "Create reusable command procedures for common turns."}],
            ["Known start and direction", "Three distinct commands", "A complete route", "Obstacle response", "Visible command feedback", "One sequence repair"],
            "The hamster follows the commands it receives, including the bad ones. Students track position and direction, put actions in order, and find the first command that sends the route astray.",
            "events-and-commands",
            ["events-and-commands", "coordinates", "debugging"],
        ),
        "quiz-of-questionable-knowledge": project_entry(
            "Quiz of Questionable Knowledge",
            "scratch",
            "Scratch",
            "Guided Class Project",
            "guided",
            "Beginner / Builder",
            "45-70 minutes",
            "Build a quiz that checks answers, gives useful feedback, keeps score, and knows which question comes next.",
            "Answer useful questions while the host insists that at least one distractor involves moon cheese.",
            ["Conditions", "Variables", "Input", "Messages", "State", "Debugging"],
            ["Several original questions", "Answer input", "Correct and incorrect branches", "Score", "Question progression", "End summary and restart"],
            ["True/false conditions", "Text comparison", "Score updates", "Question state", "Feedback", "Testing alternate inputs"],
            ["Browser", "Scratch editor", "Keyboard", "Student-written questions"],
            "Use original questions with factual answers. Do not ask players for personal information.",
            [
                step("Write three questions", "Choose clear questions with verifiable answers.", "Each question has one stated expected answer.", "Using opinion as a scored fact."),
                step("Ask and capture input", "Use the answer input for one question at a time.", "The current answer is inspectable.", "Checking an old answer variable."),
                step("Create two branches", "Give distinct feedback for correct and incorrect responses.", "Both branches can be demonstrated.", "An else is attached to the wrong condition."),
                step("Track score and question", "Update score once and advance the current question.", "One answer cannot score twice.", "Several scripts change score."),
                step("Finish and restart", "Show a summary, then reset score and question state.", "A new quiz begins cleanly.", "Question state remains at the end."),
            ],
            ["Does capitalization matter?", "Can one answer score twice?", "Does every wrong answer advance?", "Can the quiz skip a question?", "Does restart reset score and question state?"],
            ["Comparing numbers and text incorrectly.", "Score changes in several scripts.", "Feedback does not match the branch.", "The next question begins before feedback is readable."],
            ["Accept equivalent answers.", "Add categories.", "Choose questions randomly without repeats.", "Explain the final score by topic."],
            [{"name": "Builder", "description": "Create five reliable questions."}, {"name": "Inventor", "description": "Accept two forms of an answer and explain why."}, {"name": "Boss Level", "description": "Build non-repeating randomized question selection."}],
            ["Original questions", "Correct and incorrect paths", "Reliable score", "Question progression", "End summary", "One repaired condition bug"],
            "Every answer passes through a condition. Students write those comparisons, manage the question number and score, and decide whether inputs such as different capitalization should count.",
            "conditions-and-decisions",
            ["conditions-and-decisions", "variables-and-state", "events-and-commands"],
        ),
        "robot-maze-logic": project_entry(
            "Robot Maze Logic",
            "robotics",
            "Robotics and Electronics",
            "Guided Class Project",
            "guided",
            "Beginner",
            "45-70 minutes",
            "Write a robot route, predict where it will end, and trace the first command that goes wrong.",
            "Deliver a repair part through a maze using instructions precise enough for a robot that cannot guess what 'go around it' means.",
            ["Commands", "Sequences", "Movement", "Direction", "Coordinates", "Debugging"],
            ["A maze or grid", "A known start and direction", "A command vocabulary", "A predicted route", "A tested revision", "A demonstration trace"],
            ["Decomposition", "Sequence order", "Direction tracking", "Prediction", "Route testing", "Debugging one command"],
            ["Paper and pencil or browser simulation", "Optional floor grid", "No robot hardware required"],
            "This works on paper or in a grid simulation. Physical robot hardware is optional and depends on the class setup.",
            [
                step("Define the command language", "Choose exact forward, turn, and stop commands.", "Every command has one meaning.", "Using vague human directions."),
                step("Mark start and direction", "Record both position and facing direction.", "Another student can reproduce the setup.", "Recording position but not direction."),
                step("Predict the route", "Write the complete sequence before testing.", "The final position is predicted.", "Changing commands during the first run."),
                step("Trace or simulate", "Run one command at a time and record state.", "The failure point is identifiable.", "Skipping intermediate states."),
                step("Repair the first error", "Change the earliest incorrect command and run the route again.", "You can explain why the change should work.", "Rewriting the whole route at random."),
            ],
            ["Does the route track facing direction?", "Can the robot cut through corners?", "What happens at the edge?", "Does stop occur at the target?", "Can another student follow the same commands?"],
            ["Directions assume a human viewpoint.", "Turns are confused with movement.", "The robot is treated as a point with no size.", "Several commands are revised at once."],
            ["Find a shorter route.", "Add one blocked square.", "Create a reusable turn routine.", "Swap command lists with another student."],
            [{"name": "Builder", "description": "Complete and trace one route."}, {"name": "Inventor", "description": "Optimize the route after proving it works."}, {"name": "Boss Level", "description": "Design a maze and command verifier for another student."}],
            ["Command vocabulary", "Known start and direction", "Written prediction", "Complete trace", "One evidence-based repair", "Final route explanation"],
            "Students translate a route into commands and keep track of both position and direction after each one. When prediction and result differ, they repair the earliest mismatch instead of guessing at the whole route.",
            "robot-commands-and-sequences",
            ["events-and-commands", "coordinates", "debugging"],
        ),
        "led-traffic-light": project_entry(
            "LED Traffic Light",
            "robotics",
            "Robotics and Electronics",
            "Guided Demonstration",
            "demonstration",
            "Beginner / Builder",
            "40-70 minutes",
            "Program a timed traffic light, then add a pedestrian request without creating an unsafe transition.",
            "Keep a tiny intersection orderly with outputs, timing, and a sequence that does not show red and green together.",
            ["Output", "Sequences", "Timing", "Loops", "State", "Debugging"],
            ["Three visible light states", "A timed sequence", "Safe transition rules", "Optional pedestrian request", "Repeat behaviour", "Reset state"],
            ["Digital output", "Sequence timing", "State transitions", "Loops", "Safety constraints", "Testing impossible combinations"],
            ["Browser circuit simulator or paper state diagram", "Optional LEDs and suitable supervised components"],
            "The state diagram and simulator version need no hardware. A physical build uses teacher-arranged components under supervision; availability is confirmed separately.",
            [
                step("Name the states", "Define STOP, READY, and GO before wiring or coding.", "Each state has one light pattern.", "Starting with timing before defining states."),
                step("Test one output", "Make one simulated or physical LED turn on and off.", "The output responds reliably.", "Using the wrong output or connection."),
                step("Create the sequence", "Move through states in a safe order.", "Red and green are never active together.", "Several scripts control the same lights."),
                step("Add timing", "Choose readable delays and repeat the cycle.", "A full cycle is easy to observe.", "Delays are too short to inspect."),
                step("Test a request", "Optionally add a button-request state without interrupting unsafely.", "The request is handled at a defined point.", "Button input jumps directly to an unsafe state."),
            ],
            ["Can red and green appear together?", "Does restart begin from STOP?", "Can a request interrupt any state?", "Does the loop preserve sequence order?", "Can every output be tested alone?"],
            ["Outputs are controlled from competing scripts.", "Timing hides a wrong state order.", "Reset begins at an unsafe state.", "A button press is read but not acknowledged."],
            ["Add a pedestrian signal.", "Display the current state.", "Add a night flashing mode.", "Draw a complete state transition map."],
            [{"name": "Builder", "description": "Create a reliable three-state loop."}, {"name": "Inventor", "description": "Add a queued pedestrian request."}, {"name": "Boss Level", "description": "Design and test normal and night operating modes."}],
            ["State diagram", "Three outputs", "Safe sequence", "Readable timing", "Complete reset", "One impossible-state test"],
            "Students name each light state, put the states in a safe order, and check that red and green never appear together. Timing matters, but so does what the circuit is allowed to do between delays.",
            None,
            ["input-and-output", "loops-and-repetition", "variables-and-state"],
        ),
        "button-and-buzzer-alarm": project_entry(
            "Button and Buzzer Alarm",
            "robotics",
            "Robotics and Electronics",
            "Guided Class Project",
            "guided",
            "Beginner",
            "40-65 minutes",
            "Connect a button to a visible and audible alarm, then write clear rules for arming, triggering, and resetting it.",
            "Protect a small imaginary vault with an alarm useful enough to detect a press and polite enough to stop.",
            ["Input", "Output", "Events", "Conditions", "State", "Circuits"],
            ["A button input", "A buzzer or simulated sound", "Visible status output", "Armed and disarmed states", "Acknowledgement or reset", "Test cases"],
            ["Input-process-output", "Digital signals", "Conditions", "State", "Feedback", "Circuit or simulation debugging"],
            ["Browser circuit simulator", "Optional button, buzzer, microcontroller, and suitable supervised components"],
            "The circuit can be built in a browser simulator. A physical version uses teacher-arranged components and a safe buzzer volume.",
            [
                step("Read the button", "Display or log pressed and not-pressed states.", "Input changes are visible.", "Code listens to the wrong input."),
                step("Control one output", "Connect the input condition to sound or a simulated buzzer.", "The output responds for a clear reason.", "The buzzer never turns off."),
                step("Add visible feedback", "Show ARMED, TRIGGERED, or DISARMED.", "The current state is always understandable.", "Display and output disagree."),
                step("Create reset behaviour", "Choose how the alarm stops and returns to armed.", "Reset does not immediately retrigger.", "The pressed button remains true during reset."),
                step("Test sequences", "Try press, hold, release, reset, and repeated press.", "Every sequence has a defined result.", "Only a quick tap is tested."),
            ],
            ["What happens while the button is held?", "Can the alarm be disarmed?", "Does reset retrigger immediately?", "Does visual state match sound?", "Can repeated presses break state?"],
            ["The output has no off path.", "State display is decorative rather than connected.", "Reset ignores the current input.", "Sound volume or duration is not considered."],
            ["Add a delay before arming.", "Require an acknowledgement input.", "Count trigger events.", "Create a silent visual alarm mode."],
            [{"name": "Builder", "description": "Make press and release behaviour reliable."}, {"name": "Inventor", "description": "Add armed, triggered, and reset states."}, {"name": "Boss Level", "description": "Design two inputs and a clear alarm priority rule."}],
            ["Readable input", "Controlled output", "Visible state", "Reliable reset", "Held-button test", "One state bug explained"],
            "The button supplies an input; the program decides what that input means. Students connect the reading to sound, a status display, and the alarm's current state, then test presses, holds, releases, and resets.",
            "sensors-as-questions",
            ["input-and-output", "sensors", "conditions-and-decisions"],
        ),
        "conductors-and-insulators-lab": project_entry(
            "Conductors and Insulators Lab",
            "robotics",
            "Robotics and Electronics",
            "Computer Lab Project",
            "lab",
            "Builder",
            "45-75 minutes",
            "Test which materials complete a low-voltage circuit, record the evidence, and investigate readings that do not make sense.",
            "Find out whether a paperclip, wooden craft stick, or other approved material closes the circuit. A surprising result earns a second test.",
            ["Circuits", "Input", "Conductivity", "Variables", "Testing", "Evidence"],
            ["A safe low-voltage test method or simulation", "A material list", "Predictions", "Observed results", "A classification rule", "A final explanation"],
            ["Closed circuits", "Conductivity", "Controlled tests", "Recording evidence", "Classification", "Unexpected results"],
            ["Paper planning and browser simulator", "Physical version requires teacher-selected low-voltage components and safe materials"],
            "For a physical test, use only teacher-arranged low-voltage components and approved materials. Never test outlets, mains electricity, unknown liquids, or unsafe materials.",
            [
                step("Define a safe test", "Identify what will count as a completed circuit.", "The test has one visible output.", "Using an unsafe or uncontrolled power source."),
                step("Choose materials", "Select ordinary teacher-approved samples and predict results.", "Predictions are recorded before testing.", "Changing sample size and connection method together."),
                step("Run one controlled comparison", "Keep circuit and contact points consistent.", "The output difference can be observed.", "Loose contact is mistaken for insulation."),
                step("Record evidence", "Track predicted and observed results separately.", "Every classification has a recorded test.", "Remembering results instead of recording them."),
                step("Investigate surprises", "Retest one unexpected material and inspect connections.", "The conclusion acknowledges test limits.", "Changing the classification after one weak contact."),
            ],
            ["Is the circuit itself working?", "Are contact points consistent?", "Was each result repeated?", "Could coating affect the result?", "Does classification match the recorded evidence?"],
            ["Loose connections create false negatives.", "The indicator is not tested first.", "Samples differ in several uncontrolled ways.", "A prediction is rewritten after the test."],
            ["Build a result table.", "Test coated and uncoated versions safely.", "Create a mystery-material challenge.", "Explain one ambiguous result."],
            [{"name": "Builder", "description": "Classify five teacher-approved materials."}, {"name": "Inventor", "description": "Improve the test to reduce contact errors."}, {"name": "Boss Level", "description": "Design a fair mystery-material protocol for another group."}],
            ["Safe test plan", "Recorded predictions", "Controlled comparisons", "Evidence table", "Retested surprise", "Qualified conclusion"],
            "Students predict, test, and record each material under the same conditions. An odd result means checking the contacts and the circuit before deciding that the material is unusual.",
            None,
            ["input-and-output", "sensors", "debugging"],
        ),
        "microbit-reaction-timer": project_entry(
            "micro:bit Reaction Timer",
            "robotics",
            "Robotics and Electronics",
            "Guided Class Project",
            "guided",
            "Builder",
            "50-80 minutes",
            "Build a reaction timer with a random delay, an early-press rule, and results in the correct units.",
            "Wait for an unpredictable signal, press as quickly as possible, and make the timer distrust suspiciously early presses.",
            ["Input", "Timing", "Variables", "Randomness", "State", "Testing"],
            ["A waiting state", "Random start delay", "Visible go signal", "Button response", "Measured elapsed time", "Early-press and restart rules"],
            ["Microcontroller input", "Elapsed time", "Random delay", "State", "Fair tests", "Measurement limits"],
            ["Physical version requires a micro:bit and suitable connection method", "A browser micro:bit simulator can support logic work"],
            "A physical build requires a micro:bit, with availability confirmed before class. The same timing logic can be worked out in a compatible browser simulator.",
            [
                step("Create the waiting state", "Show that the test is ready but not started.", "Button presses have a defined waiting result.", "The timer begins immediately."),
                step("Add random delay", "Wait an unpredictable but bounded amount.", "Several runs use different delays.", "The delay range includes unusable values."),
                step("Show the go signal", "Record start time and display a clear cue.", "The cue and start timestamp happen together.", "Timing begins before the cue."),
                step("Measure the response", "Read the button and calculate elapsed time.", "A plausible result is displayed once.", "Repeated button input overwrites the result."),
                step("Handle early presses", "Detect a press before GO and reset fairly.", "Cheating or mistakes produce a clear state.", "An early press is counted as a perfect score."),
            ],
            ["Can the same random delay repeat?", "What happens on an early press?", "Can holding the button trigger GO?", "Is time measured in the intended unit?", "Does a new test clear the old result?"],
            ["Start time is recorded too early.", "Button state carries into the test.", "Units are mislabeled.", "Old results remain active during restart."],
            ["Store several attempts.", "Show best and average results.", "Add false-start count.", "Compare two input methods and discuss fairness."],
            [{"name": "Builder", "description": "Produce one reliable reaction measurement."}, {"name": "Inventor", "description": "Store and compare three attempts."}, {"name": "Boss Level", "description": "Design a fair two-player protocol and explain its limits."}],
            ["Waiting state", "Random delay", "Synchronized start cue", "Measured response", "Early-press handling", "One fairness limitation"],
            "Students coordinate the start signal and timestamp, calculate elapsed time, and decide how to handle a button pressed too early. Comparing results also raises useful questions about units and fair tests.",
            "sensors-as-questions",
            ["sensors", "variables-and-state", "debugging"],
        ),
        "robot-patrol-challenge": project_entry(
            "Robot Patrol Challenge",
            "robotics",
            "Robotics and Electronics",
            "Computer Lab Project",
            "lab",
            "Builder / Inventor",
            "60-100 minutes",
            "Design a repeating patrol that notices an obstacle, tries a response, and checks whether the response worked.",
            "Patrol a route until an obstacle appears, then choose a response that does not involve turning forever in a corner.",
            ["Loops", "Sensors", "Conditions", "State", "Feedback", "Autonomy"],
            ["A repeatable patrol", "An obstacle signal", "At least one response state", "A correction and recheck", "A stop rule", "A demonstration scenario"],
            ["Sense-Decide-Act", "Feedback loops", "State", "Recovery logic", "Edge-case testing", "Limits of autonomy"],
            ["Paper state machine or browser simulation", "Optional robot platform and teacher-arranged sensors"],
            "The patrol can be designed as a state machine or built in a browser simulation. A physical robot and sensors are optional and depend on the class setup.",
            [
                step("Define the patrol", "Choose a short route and what counts as one cycle.", "The normal route repeats reliably.", "The route has no known start."),
                step("Define the sensor question", "Choose the reading that will count as evidence of an obstacle.", "Normal and blocked readings are distinguishable.", "Treating the sensor reading as the decision itself."),
                step("Create response state", "Stop, turn, signal, or choose another route.", "Obstacle input changes state once.", "Every reading starts a new response."),
                step("Recheck after acting", "Sense again before returning to patrol.", "The correction is tested rather than assumed.", "The system returns to patrol blindly."),
                step("Test traps", "Try corners, repeated obstacles, and sensor noise.", "At least one recovery failure is repaired.", "Only an empty route is tested."),
            ],
            ["Does patrol repeat from a known state?", "What exact signal means obstacle?", "Can recovery loop forever?", "Does the system recheck?", "Is there a human stop rule?"],
            ["Obstacle checks happen outside the patrol loop.", "Recovery has no exit condition.", "State is changed in several places.", "Successful movement is called intelligence without explaining rules."],
            ["Add a second recovery route.", "Count patrol cycles.", "Signal for human help after repeated failure.", "Compare two feedback strategies."],
            [{"name": "Builder", "description": "Stop and signal reliably at an obstacle."}, {"name": "Inventor", "description": "Correct course and rejoin patrol after checking again."}, {"name": "Boss Level", "description": "Track failed options and request human help at a defined limit."}],
            ["Normal patrol", "Sensor question", "Decision rule", "Correction", "Recheck", "One stated autonomy limit"],
            "Students build the patrol as a feedback loop: read the sensor, choose an action, then read it again. They also set an exit condition so the robot can stop or ask for help instead of turning forever.",
            "robot-patrol-logic",
            ["feedback", "sensors", "autonomy"],
        ),
        "obby-basics": project_entry(
            "Obby Basics",
            "roblox",
            "Available Later",
            "Future Program Preview",
            "preview",
            "Future Builder",
            "Not scheduled",
            "A planned Roblox Studio obstacle course using 3D coordinates, touch events, checkpoints, and reset rules.",
            "Design a short obstacle course whose jumps and hazards are readable, fair, and held together by reliable checkpoints.",
            ["Lua", "3D Space", "Properties", "Events", "Collision", "Game State"],
            ["A small original obstacle course", "Spawn and checkpoint logic", "Hazard rules", "A finish state", "Readable difficulty progression"],
            ["Roblox Studio objects", "Coordinates in 3D", "Properties", "Touch events", "Functions", "Player state"],
            ["Roblox Studio and an appropriate account setup"],
            "Roblox Studio and account arrangements will be confirmed when the program opens.",
            [],
            ["Could a player skip the intended route?", "Does checkpoint state reset correctly?", "Are hazards readable before contact?"],
            ["Building decoration before game rules.", "Unfair invisible collision.", "Checkpoint scripts disagree.", "Copied models introduce unknown behaviour."],
            ["Map a difficulty curve.", "Design one reusable checkpoint function.", "Explain every external asset before using it."],
            [{"name": "Builder", "description": "Build one reliable checkpoint."}, {"name": "Inventor", "description": "Write one reusable hazard rule."}, {"name": "Boss Level", "description": "Ask another player to test the course, then revise one unfair section."}],
            ["An original level layout", "One Lua event explained", "Reliable checkpoint state"],
            "When this program opens, the obby will provide a practical route into 3D coordinates, object properties, touch events, state, and Lua. Students will also inspect every borrowed asset before it enters the game.",
            None,
            ["coordinates", "events-and-commands", "sensing-and-collision"],
            status="Available later",
        ),
        "coin-collector-world": project_entry(
            "Coin Collector World",
            "roblox",
            "Available Later",
            "Future Program Preview",
            "preview",
            "Future Builder / Inventor",
            "Not scheduled",
            "A planned Roblox Studio project using collection events, score, reusable Lua, and a small NPC state machine.",
            "Build a small original world where collected objects change the score, open a route, and give one NPC a clear job.",
            ["Lua", "Events", "Variables", "Functions", "Scoring", "NPC State"],
            ["Original 3D space", "Collectible objects", "Server-aware score concept", "Reusable collection logic", "A simple NPC state"],
            ["Lua variables", "Events", "Functions", "Object references", "State", "Multiplayer responsibility"],
            ["Roblox Studio and an appropriate account setup"],
            "Roblox Studio and account arrangements will be confirmed when the program opens.",
            [],
            ["Can one coin score twice?", "Does score survive the intended scope?", "Can copied scripts disagree?"],
            ["One script per coin creates duplication.", "Client display is confused with authoritative state.", "NPC behaviour has no state limit.", "Unreviewed models add scripts."],
            ["Plan a reusable collection function.", "Design a non-repeating reward route.", "Give an NPC a two-state behaviour."],
            [{"name": "Builder", "description": "Make each object add to the score once."}, {"name": "Inventor", "description": "Reuse one collection system across several objects."}, {"name": "Boss Level", "description": "Connect the collection state to a simple NPC or gate."}],
            ["One reliable collection event", "Visible score and world state", "Reusable Lua explained"],
            "This project will move from familiar game rules into text-based scripting. Students will reuse functions, track score, and decide which changes belong to one player and which belong to the shared world.",
            None,
            ["events-and-commands", "variables-and-state", "autonomy"],
            status="Available later",
        ),
        "ai-guessing-game": project_entry(
            "AI Guessing Game",
            "ai",
            "Available Later",
            "Future Program Preview",
            "preview",
            "Future Builder",
            "Not scheduled",
            "A planned investigation of pattern-based guesses, confidence, errors, and fair testing.",
            "Test a small guessing system with new examples and find out where its confident answers stop matching the evidence.",
            ["Patterns", "Prediction", "Classification", "Testing", "Bias", "Human Judgment"],
            ["A transparent guessing rule or future model", "A test set", "Recorded correct and incorrect results", "An error explanation", "A human verification step"],
            ["Patterns versus understanding", "Training and testing distinction", "Classification", "Confidence limits", "Bias", "Evaluation"],
            ["Class tools selected and reviewed before use"],
            "Tools, accounts, and any data use will be reviewed before the program opens.",
            [],
            ["Was the test data seen during setup?", "Are classes balanced?", "Does confidence match correctness?", "Can a person explain the error categories?"],
            ["Testing with the same examples used to create the rule.", "Calling pattern matching understanding.", "Reporting only successful guesses.", "Collecting unnecessary personal data."],
            ["Create an error table.", "Compare two transparent rules.", "Design a harder fair test.", "Add a required human-check step."],
            [{"name": "Builder", "description": "Test a visible rule with new examples."}, {"name": "Inventor", "description": "Compare two approaches and sort their errors."}, {"name": "Boss Level", "description": "Design a test that exposes confident mistakes."}],
            ["The pattern explained", "Incorrect cases shown", "One limitation stated"],
            "Students will inspect the pattern behind each guess and test it on examples it has not seen. Wrong answers stay in the results; they are often the most useful part.",
            None,
            ["conditions-and-decisions", "debugging", "autonomy"],
            status="Available later",
        ),
        "chatbot-character-lab": project_entry(
            "Chatbot Character Lab",
            "ai",
            "Available Later",
            "Future Program Preview",
            "preview",
            "Future Inventor",
            "Not scheduled",
            "A planned writing and testing lab about prompts, character rules, inconsistent answers, and verification.",
            "Write rules for a fictional chatbot character, test whether it follows them, and collect the answers that sound better than they are.",
            ["Prompts", "Language", "State", "Testing", "Safety", "Human Judgment"],
            ["An original fictional character brief", "Behaviour rules", "A test conversation set", "Failure categories", "A revision log", "Clear safety limits"],
            ["Prompt constraints", "Consistency", "Model limitations", "Evaluation", "Authorship", "Responsible use"],
            ["Class tools, accounts, and privacy setup reviewed before use"],
            "Tools and account arrangements will be reviewed before the program opens. Students will not put personal information into prompts.",
            [],
            ["Does the character invent facts?", "Does it follow conflicting instructions?", "Can it admit uncertainty?", "Are tests free of personal information?"],
            ["Treating fluent text as evidence.", "Using personal details in prompts.", "Changing the prompt without recording why.", "Calling inconsistent outputs personality."],
            ["Create a red-team question set.", "Compare two character rules.", "Add an uncertainty response requirement.", "Write a human verification checklist."],
            [{"name": "Builder", "description": "Define and test three character rules."}, {"name": "Inventor", "description": "Sort the failures and revise one prompt rule."}, {"name": "Boss Level", "description": "Write a safety and verification checklist for another group."}],
            ["Original character rules", "Recorded failures", "One clear safety boundary"],
            "Students will treat the prompt as a set of instructions and the responses as material to inspect. Fluent writing still needs fact-checking, especially when the bot sounds certain.",
            None,
            ["events-and-commands", "variables-and-state", "debugging"],
            status="Available later",
        ),
    }
)


PROGRAM_NAMES = {
    "scratch": "Scratch & Game Design",
    "robotics": "Robotics",
    "roblox": "Roblox Studio / Lua",
    "ai": "AI & Smart Machines",
}


LAB_NOTES = {
    "the-suspiciously-emotional-space-pet": "Choose the pet's needs and the rules connecting them. The finished version must show how its current values produce its visible mood.",
    "conductors-and-insulators-lab": "Choose teacher-approved samples and a consistent test method. Record predictions first, repeat surprising results, and keep the low-voltage safety rules fixed.",
    "robot-patrol-challenge": "Choose the patrol route and recovery action. The system must read the obstacle signal again after acting and stop at a defined limit.",
}


for project_slug, project in PROJECTS.items():
    if project_slug in LAB_NOTES:
        project["lab_note"] = LAB_NOTES[project_slug]
    project["slug"] = project_slug
    project["url"] = f"/projects/{project_slug}"
    project.setdefault("program_key", "scratch")
    project.setdefault("group", "Scratch")
    project.setdefault("project_type", "Computer Lab Project" if project.get("mode") == "lab" else "Guided Class Project")
    project.setdefault("status", project["project_type"])
    project.setdefault("status_class", "lab" if project.get("mode") == "lab" else "active")
    project.setdefault("card_summary", project.get("mission", "A School of Code project."))
    project.setdefault("what_students_build", project.get("required_systems", []))
    project.setdefault("what_students_learn", project.get("topics", []))
    project.setdefault("needs", ["Browser", "Scratch editor", "Keyboard"] if project["program_key"] == "scratch" else ["Project-specific setup confirmed before class"])
    project.setdefault("setup_note", project.get("needs_note", project.get("lab_note", "Setup depends on the selected project format.")))
    project.setdefault("test_questions", project.get("test_questions", [f"Can the student demonstrate {item.lower()}?" for item in project.get("checkpoints", [])]))
    project.setdefault("common_mistakes", ["Testing only the easiest successful path.", "Changing several systems before retesting.", "Resetting only part of the project state."])
    project.setdefault("improvements", project.get("challenge_cards", []))
    project.setdefault("challenge_levels", [
        {"name": "Builder", "description": "Complete and explain the required systems."},
        {"name": "Inventor", "description": "Choose one challenge card and test the result."},
        {"name": "Boss Level", "description": project.get("boss_level", "Combine systems while preserving a reliable reset.")},
    ])
    project.setdefault("lesson_slug", "coordinates-and-movement" if project_slug in COORDINATE_PROJECTS else None)
    project.setdefault("related_topics", [project.get("topic_endpoint", "coordinates").replace("_topic", "")])
    project["program"] = PROGRAM_NAMES[project["program_key"]]
    project["meta_description"] = project.get("meta_description") or f"{project['name']}: {project['card_summary']}"
    for download in project.get("downloads", []):
        download_path = STATIC_ROOT / "projects" / project_slug / download["filename"]
        download["size_bytes"] = download_path.stat().st_size if download_path.exists() else 0
        download["size_label"] = f"{download['size_bytes'] / 1024:.1f} KB" if download["size_bytes"] else "Build required"
        download["url"] = f"/projects/{project_slug}/downloads/{download['filename']}"


PROJECT_ORDER = [
    "escape-from-the-giant-pigeon",
    "attack-of-the-angry-snowballs",
    "the-suspiciously-emotional-space-pet",
    "the-floor-is-definitely-lava",
    "robot-hamster-command-centre",
    "quiz-of-questionable-knowledge",
    "grandmas-intergalactic-taxi",
    "astro-chicken-rescue",
    "robot-maze-logic",
    "led-traffic-light",
    "button-and-buzzer-alarm",
    "conductors-and-insulators-lab",
    "microbit-reaction-timer",
    "robot-patrol-challenge",
    "obby-basics",
    "coin-collector-world",
    "ai-guessing-game",
    "chatbot-character-lab",
]
